version: '3'
services:
  web:
    build:
      #where we want all our files and folders for our
      #project to be pulled from, here it is essentially 
      #from the same folder as docker-compose
      context: .
      #location of docker file to create image
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]